### ISSUE TITLE
BSW命令でPCが進まない

### ISSUE THREAD

**Issue by yamam** [toppers/athrill-target-rh850f1x#23]
BSW命令を実行するop_exec_bsw_12でPCの値を変化させていませんので、無限ループになります。
他にもop_exec_bsh_12等でPCの値を変化させていないようでした。

**Comment by tmori** [comment]
ご連絡ありがとうございます．
調査してみます．

**Comment by tmori** [comment]
cpu_exec/op_exec_xx.c の全ファイルを目視確認したところ，以下のファイル/関数で類似の問題がありました．

- op_exec_logic.c/op_exec_bsw_12
- op_exec_logic.c/op_exec_bsh_12
- op_exec_logic.c/op_exec_hsw_12
- op_exec_logic.c/op_exec_hsh_12
