### ISSUE TITLE
実行クロック数について

### ISSUE THREAD

**Issue by yamam** [toppers/athrill-target-rh850f1x#31]
命令の実行サイクル(op_exec_table)はどのように算出しているのでしょうか？
例えばop_exec_div_11は19となっていますが、RH850は20、V850は35となっており、どちらとも違っています。
https://www.renesas.com/jp/ja/document/mas/rh850g3kh-users-manual-software?language=ja (P.355)
https://www.renesas.com/jp/ja/document/mat/v850e2-architecture-preliminary?language=ja (P.163)

また、issue(命令実行直後に他の命令を実行する場合)とlatency(命令実行結果をその命令実行直後の命令で利用する場合)
で値が違う場合、どのように実行サイクル数を決めているのでしょうか？

**Comment by tmori** [comment]
> また、issue(命令実行直後に他の命令を実行する場合)とlatency(命令実行結果をその命令実行直後の命令で利用する場合)
> で値が違う場合、どのように実行サイクル数を決めているのでしょうか？
athrillのCPU再現レベルは，命令レベルで，サイクルレベルの再現はしておりません．
ただ，シミュレーション実行時にどの程度のクロック消費したかを把握するための手段として，
実行サイクルの参考数値を埋めている程度となります．

ですので，issueとlatencyの違いに対応するような設計は含まれておりません．

> 命令の実行サイクル(op_exec_table)はどのように算出しているのでしょうか？
命令の実行サイクルについては，当時開発していたマニュアルを参照して埋めた記憶があります．
ご提示いただいたマニュアルとは異なるものと思います．

**Comment by yamam** [comment]
> 命令の実行サイクルについては，当時開発していたマニュアルを参照して埋めた記憶があります．
もしかしてRH850G3KとRH850G3KGでは実行サイクル数が違うのでしょうか？
RH850G3Kのマニュアルは公開されていないようです。

**Comment by tmori** [comment]
> もしかしてRH850G3KとRH850G3KGでは実行サイクル数が違うのでしょうか？
詳細は把握しておりませんが，実行サイクル数は異なっていたと思われます．

**Comment by tmori** [comment]
本件，ご質問内容はすべて回答させていただいたと思いますので，クローズいたします．

**Comment by yamam** [comment]
RH850G3Kのマニュアルが手元にあったので確認しました。
DIVのクロックは、issue、repeat、latencyともに36となっていました。(2016.04.25 Rev.1.20)

**Comment by yamam** [comment]
https://github.com/toppers/athrill-target-rh850f1x にSupport target groupとして
RH850G3KHユーザーズマニュアル ソフトウェア編
が記載されていましたので、このpdfに記載されているサイクル数に合わせた方がいいかと思いました。
